
global:
 resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  receiver: default-receiver

  routes:
    - match:
        severity: warning
      receiver: slack-warning

    - match:
        severity: critical
      receiver: slack-critical

receivers:
  - name: default-receiver
    slack_configs:
      - api_url: 'https://hooks.slack.com/URL'
        channel: '#monitoring-alerts'
        send_resolved: true
        text: |
          *[{{ .Status | toUpper }}]* {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}

  - name: slack-warning
    slack_configs:
      - api_url: 'https://hooks.slack.com/URL'
        channel: '#monitoring-warning-alerts'
        send_resolved: true
        text: |
          *[{{ .Status | toUpper }}]* {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}

  - name: slack-critical
    slack_configs:
      - api_url: 'https://hooks.slack.com/URL'
        channel: '#monitoring-alerts'
        send_resolved: true
        text: |
          *[{{ .Status | toUpper }}]* {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}

