apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-app
      image: nginx   # you can replace this with your app image
      ports:
        - containerPort: 4040

