apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: nginx-app
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
    - name: metrics
      port: 4040
      targetPort: 4040

