apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app-servicemonitor
  namespace: nginx-app
  labels:
    release: prom-stack     # IMPORTANT — must match your Prometheus Helm release
spec:
  selector:
    matchLabels:
      app: nginx-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

